name: Bug Report
description: Report a bug or issue with the plugin
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure the plugin with...
        2. Player joins with...
        3. See error...
    validations:
      required: true

  - type: input
    id: server-version
    attributes:
      label: Server Version
      description: Your server version (output of /version)
      placeholder: e.g., Paper 1.21.1
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: The version of ModDetectorPlugin you're using
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Plugin Configuration
      description: Your config.yml (remove any sensitive information)
      render: yaml
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Any relevant error messages or logs
      render: text
    validations:
      required: false
